### ISSUE TITLE
Remove obsolete :underscore? from docs and spec

### ISSUE THREAD

**Issue by zharinov** [kkinnear/zprint#220] opened 2022-02-16 15:19 UTC
I've found the `:underscore?` key for `:justify` option, which has this spec:
https://github.com/kkinnear/zprint/blob/aadf466c84ee928a842c3adc9ed25847f159c024/src/zprint/spec.cljc#L206

However, seems like it's invalid:
https://github.com/kkinnear/zprint/blob/aadf466c84ee928a842c3adc9ed25847f159c024/src/zprint/spec.cljc#L208

Though I've also found the initialization in the code, seems like it's unused variable actually:
https://github.com/kkinnear/zprint/blob/b76b692ab215116131a151d5042ac16f4a58c632/src/zprint/zprint.cljc#L1384

I would be happy to have this option available. Please, add this option if this isn't a big deal in terms of code changes.

**Comment by kkinnear** [comment] 2022-02-16 17:03
Yes, I appear to have changed direction while dealing with short things in justification.  The `:underscore?` key turned into a set of string to not justify.  [Here](https://cljdoc.org/d/zprint/zprint/1.2.2/doc/zprint-reference#no-justify--set-of-strings-or-nil) is the `cljdoc` for this stuff.  As near as I can recollect, the `:underscore?` key was designed to just not justify underscores, and I decided to generalize things a bit by having a set of strings that would not be justified.

So the `:no-justify` key subsumes what my plans were for the `:underscore?` key.  I need to fix the doc and the spec to get rid of it, since my original intent is more than met by the `:no-justify` key.

In any case, what would you like zprint to do that it doesn't already?  If you could give me an example of what you would like to have happen, I might be able to give you something to put in your options map that would do that for you without a new release.  Failing that, I'm always interested in new capabilities to meet people's need.  As you can see from the rather silly number of options that zprint has already.  So let me know what you are looking for.  A description of what you want is nice, but a description along with an example or two is really helpful.

Thanks for getting in touch!

**Comment by kkinnear** [comment] 2022-02-16 17:25
Great!  I'm glad it works for you.  I'll change the name, that way I won't forget to do it a second time!

Thanks again for getting in touch.

**Comment by kkinnear** [comment] 2022-02-16 17:30
Very few people use justification, near as I can tell.  I've worked hard to get justification to be useful, despite that.  If you find things (other things) that aren't pleasing about justification, please let me know if you have time.  Thanks!

**Comment by kkinnear** [comment] 2022-04-12 22:07
This is fixed in `1.2.3`.  Let me know if something looks off.  Thanks for reporting the problem!

**Closed** 2022-07-27 17:13 UTC
Labels: bug
