### ISSUE TITLE
Printing Datomic database values dumps the whole database

### ISSUE THREAD

**Issue by PEZ** [kkinnear/zprint#111] opened 2019-10-19 14:10 UTC
Not sure this is an issue that belongs here, but trying.

In this file: https://github.com/PEZ/nrepl-pprint-datomic/blob/master/src/nrepl_pprint_datomic/core.clj

There is this code:
```clojure
@(d/transact conn [{:db/doc "Hello world"}])
```

Evaluating it w/o pretty printing I get:

```clojure
{:db-before datomic.db.Db@defa54b7, :db-after datomic.db.Db@270efa27, :tx-data [#datom[13194139534318 50 #inst "2019-10-19T12:34:49.714-00:00" 13194139534318 true] #datom[17592186045423 62 "Hello world" 13194139534318 true]], :tempids {-9223301668109598140 17592186045423}}
```

But with `zprint` printing the content of the two database values are printed, which is a large printout (depending on the database it can get really huge).

Is there a way I can tell zprint to print just the references to the values, like ”normal” printing does?

**Comment by kkinnear** [comment] 2019-10-19 22:14
This is very much an issue that belongs here, thanks for asking. 

There are two ways that you can probably get what you want:

  1.  I'm not a datomic user, so I don't know what the `datomic.db.Db@defa54b7` thing is.  If it is an atom, then you can configure `{:atom {:object? true}}` to get "normal" printing for all atoms.  The `:object?` key works for atoms, agents, delays, futures, and promises.

2. Another approach is to simply not print those values.  You can get this behavior by using `{:map {:key-ignore [:db-before :db-after]}}`.  This will replace the values that are printed with `:zprint-ignored`, so you know they were there, but ignored.  If you want them completely missing from the map, then you can use `:key-ignore-silent`, and you will simply not see them at all.  I implemented this specifically for your use case -- someone was printing datomic information, and the database values exploded the output.

In either case, the options map can be specified on the call to zprint, you can use `(set-options ...)` at the repl or in your program, or you can configure it in your ~/.zprintrc file (which is true for all configuration options).  I might not configure `:key-ignore-silent` in my `.zprintrc` file, as then I would wonder months later why those keys were missing, but that's just me.

Hopefully #1 will get you what you want, but if not, #2 will definitely solve the problem, albeit a bit differently.

**Comment by PEZ** [comment] 2019-10-19 23:06
Thanks! The first option would definitely be the one for my use case. It's the users of Calva that run into the problem when they have pprint enabled (which is the Calva default even). With that enabled, Calva uses the cider-nrepl printer option (set to `puget` at the moment, but I also tried with `zprint` in my dev environment). Now tried with the `{:atom {:object? true}}` option, but run into a problem where the `true` gets translated to `1` somewhere in my nrepl chain (not sure where it happens). zprint then complains that it is not a boolean (which it isn't of course).

I might give that some more trying, but right now I have instead opted to move the pretty printing client side, in ClojureScript and using `zprint`. Which gives new and interesting results. 😄 Since the result from the nrepl eval is a string, zprint needs to first parse it. Which fails with a thing like `datomic.db.Db@defa54b7` with `rewrite-cljs` complaining that `defa54b7` is not a number. So I now have a dev version of Calva where it catches parsing errors and prints plain in when that happens. I think I will opt for using zprint client side for Calva's pprint needs.

**Comment by kkinnear** [comment] 2019-10-22 01:41
I may well be missing something, but if you are having trouble with the `1` not being a boolean, couldn't you do something like this in your options map: `{:atom {:object? (not (nil? x))}}`, or even more succinctly: `{:atom {:object? (boolean x)}}`, where `x` is the variable that gets passed around?  Ot the place where the `1` ends up?

Anyway, I'm glad that you have found some approach that works with zprint.

**Comment by PEZ** [comment] 2019-10-22 07:15
I can't place code where the `1` ends up, unfortunately. But I have a setup now where I can try this w/o going through nrepl, so I can defer that particular problem too later. 😄 

Using zprint client side isn't fully satisfactory. I have strings there and need to parse them to EDN before zprinting. I haven't found a way to do that that doesn't croak on that Datomic value symbol (and a lot of other things that come as results). So now experimenting server side. The `{atom {:object? true}}` setting doesn't ”bite”, so I need something else.

This is my current test case:

```clojure
(comment
  (do
    (def db-uri "datomic:mem://foo")
    (d/create-database db-uri)
    (def conn (d/connect db-uri))
    (def result @(d/transact conn [{:db/doc "Hello world"}])))
  
  (with-out-str
    (clojure.pprint/pprint result))
  ;; => {:db-before datomic.db.Db@cd87ac0d,
  ;;     :db-after datomic.db.Db@73b2c2d8,
  ;;     :tx-data
  ;;     [#datom[13194139534314 50 #inst "2019-10-22T06:53:20.308-00:00" 13194139534314 true] #datom[17592186045419 62 "Hello world" 13194139534314 true]],
  ;;     :tempids {-9223301668109598142 17592186045419}}
  ;;    
  
  
  (zprint/zprint-str result)
  ;; => {:db-after
  ;;     #datomic.db.Db
  ;;      {:asOfT nil,
  ;;       :basisT 1000,
  ;;       :elements
  ;;         [#datomic.db.Partition {:id 0, :kw :db.part/db} nil nil
  ;;     ... the whole database, same for :db-before
  )
```

So what I am after is something similar to what `pprint` does. But more like `zprint` would do it. 😄

And I can't know what keys are going to cause expansion and such. This is probably going to be happening in `cider-nrepl.

**Comment by kkinnear** [comment] 2019-10-29 16:30
I will work on this to see what I can do.  I expect I can figure out something, but as I'm not a datomic user so far, I don't have any real way to reproduce this issue. If you were to send me the result of `(type (:db-after result))` that would be interesting and let me get a start on this while I'm wrestling with learning enough about datomic to reproduce this problem.  Thanks!

**Comment by PEZ** [comment] 2019-10-29 22:04
Hello, here's what I get: `#<Class@138a7441 datomic.db.Db>`

I got it by evaluating:
```clojure
(do
   (def db-uri "datomic:mem://foo")
   (d/create-database db-uri)
   (def conn (d/connect db-uri))
   (type (:db-after @(d/transact conn [{:db/doc "Hello world"}]))))
```

Which I think is what you suggested, right?

The project https://github.com/PEZ/nrepl-pprint-datomic is setup so that you shouldn't need install Datomic. Maybe you figured that out, but anyway. From there to reproduce this I hack Calva, but more straightforward ways are probably possible, 😄

Of course I'm more than happy to try things out, but I think we're in different timezones, so turnaround times might be long.

**Comment by PEZ** [comment] 2019-10-29 22:16
I think an nrepl, server side, solution to this would benefit most people. I have tried to figure out why things are expanded there, when pretty printing, but I fail.

BTW. It's not just Datomic, it is the same with other structures as well, so if something like Pedestal is more familiar to you, I've seen it there as well.

**Comment by kkinnear** [comment] 2019-11-08 22:29
I finally have something for you.  Thank you **very** much for `nrepl-pprint-datomic`!  I didn't realize what you had created there -- it was just what I needed to debug this issue (which I suppose was the point).  Before I figured that out, I tried Datomic on-prem, with no success.  At least the simple, tutorial-level, install I performed did not replicate the problem that you are having, but the ` nrepl-pprint-datomic` repo worked great at reproducing the problem.

And this yields the following potential solution: configure the zprint library with `{:record {:to-string? true}}`. 

For example:
```clojure
nrepl-pprint-datomic.core=> (zp/zprint x {:record {:to-string? true}})
{:db-after "datomic.db.Db@3835b7bd",
 :db-before "datomic.db.Db@ba5a75ba",
 :tempids {-9223301668109598143 17592186045417},
 :tx-data
   [#datom[13194139534312 50 #inst "2019-11-08T21:48:20.939-00:00" 13194139534312 true] #datom[17592186045417 62 "hello world" 13194139534312 true]]}
nil
nrepl-pprint-datomic.core=> (clojure.pprint/pprint x)
{:db-before datomic.db.Db@ba5a75ba,
 :db-after datomic.db.Db@3835b7bd,
 :tx-data
 [#datom[13194139534312 50 #inst "2019-11-08T21:48:20.939-00:00" 13194139534312 true] #datom[17592186045417 62 "hello world" 13194139534312 true]],
 :tempids {-9223301668109598143 17592186045417}}
nil
```

Now, I believe that there is some problem getting things into the options map for zprint, though I don't fully understand what is going on there.  That said, if you execute `(zprint.core/set-options! {:record {:to-string? true}})` before you ever actually let someone use the zprint library, you should be fine.  It is kind of nice, sometimes, to see the value of records (which is the default for zprint), but it isn't terrible to just show their `toString` values all of the time -- if it means that you don't get the whole Datomic database output all of the time.

Note that `{:record {:to-string? true}}` is available in all current versions of zprint.  I hope that this can be made to work for you.  If this doesn't solve the problem, please let me know.  I could imagine some new feature where, for records, zprint would check the size of the current value, and if it was small, it would output that, and if it was large, it would use the `toString` value.  But it doesn't do that today, and it would be nice to not have to add that.

---------------------------

Another interesting capability in zprint is to use `:max-length n` or `:max-depth n` to limit output:
```clojure
nrepl-pprint-datomic.core=> (zp/zprint x {:record {:to-string? false} :max-length 4})
{:db-after #datomic.db.Db {:asOfT nil,
                           :basisT 1000,
                           :elements
                             [#datomic.db.Partition {:id 0, :kw :db.part/db} nil
                              nil #datomic.db.Partition {:id 3, :kw :db.part/tx}
                              ...],
                           :filt nil,
                           ...},
 :db-before #datomic.db.Db
             {:asOfT nil,
              :basisT 63,
              :elements [#datomic.db.Partition {:id 0, :kw :db.part/db} nil nil
                         #datomic.db.Partition {:id 3, :kw :db.part/tx} ...],
              :filt nil,
              ...},
 :tempids {-9223301668109598143 17592186045417},
 :tx-data
   [#datom[13194139534312 50 #inst "2019-11-08T21:48:20.939-00:00" 13194139534312 true] #datom[17592186045417 62 "hello world" 13194139534312 true]]}
nil
```

Limit the depth:

```clojure
nrepl-pprint-datomic.core=> (zp/zprint x {:record {:to-string? false} :max-depth 2})
{:db-after #datomic.db.Db {:asOfT nil,
                           :basisT 1000,
                           :elements ##,
                           :filt nil,
                           :history nil,
                           :id "5dc5e259-f56f-42c3-a1ae-35ed2e47d5e2",
                           :ids ##,
                           :index nil,
                           :index-rev 0,
                           :index-root-id nil,
                           :indexBasisT 0,
                           :indexing nil,
                           :indexingNextT nil,
                           :keys ##,
                           :memidx ##,
                           :memlog ##,
                           :mid-index nil,
                           :nextT 1002,
                           :raw nil,
                           :sinceT nil},
 :db-before #datomic.db.Db {:asOfT nil,
                            :basisT 63,
                            :elements ##,
                            :filt nil,
                            :history nil,
                            :id "5dc5e259-f56f-42c3-a1ae-35ed2e47d5e2",
                            :ids ##,
                            :index nil,
                            :index-rev 0,
                            :index-root-id nil,
                            :indexBasisT 0,
                            :indexing nil,
                            :indexingNextT nil,
                            :keys ##,
                            :memidx ##,
                            :memlog ##,
                            :mid-index nil,
                            :nextT 1000,
                            :raw nil,
                            :sinceT nil},
 :tempids {-9223301668109598143 17592186045417},
 :tx-data
   [#datom[13194139534312 50 #inst "2019-11-08T21:48:20.939-00:00" 13194139534312 true] #datom[17592186045417 62 "hello world" 13194139534312 true]]}
nil
```

Perhaps the most interesting way to get a feel for the shape of data is to use the `:max-length` capability with a vector, where the length at each level of depth is controlled.  The final number is used for each depth below that which shows up in the vector, so in this case the 5 is used for everything below the first level:
```clojure
nrepl-pprint-datomic.core=> (zp/zprint x {:record {:to-string? false} :max-length [1000 5]})
{:db-after #datomic.db.Db {:asOfT nil,
                           :basisT 1000,
                           :elements
                             [#datomic.db.Partition {:id 0, :kw :db.part/db} nil
                              nil #datomic.db.Partition {:id 3, :kw :db.part/tx}
                              #datomic.db.Partition {:id 4, :kw :db.part/user}
                              ...],
                           :filt nil,
                           :history nil,
                           ...},
 :db-before #datomic.db.Db
             {:asOfT nil,
              :basisT 63,
              :elements [#datomic.db.Partition {:id 0, :kw :db.part/db} nil nil
                         #datomic.db.Partition {:id 3, :kw :db.part/tx}
                         #datomic.db.Partition {:id 4, :kw :db.part/user} ...],
              :filt nil,
              :history nil,
              ...},
 :tempids {-9223301668109598143 17592186045417},
 :tx-data
   [#datom[13194139534312 50 #inst "2019-11-08T21:48:20.939-00:00" 13194139534312 true] #datom[17592186045417 62 "hello world" 13194139534312 true]]}
nil
nrepl-pprint-datomic.core=> 
```
Here is one which limits the second level to a maximum length of 5 and doesn't allow anything at any level below that:
```clojure
nrepl-pprint-datomic.core=> (zp/zprint x {:record {:to-string? false} :max-length [1000 5 0]})
{:db-after #datomic.db.Db {:asOfT nil,
                           :basisT 1000,
                           :elements ##,
                           :filt nil,
                           :history nil,
                           ...},
 :db-before #datomic.db.Db {:asOfT nil,
                            :basisT 63,
                            :elements ##,
                            :filt nil,
                            :history nil,
                            ...},
 :tempids {-9223301668109598143 17592186045417},
 :tx-data
   [#datom[13194139534312 50 #inst "2019-11-08T21:48:20.939-00:00" 13194139534312 true] #datom[17592186045417 62 "hello world" 13194139534312 true]]}
nil
```
Anyway, I'm not suggesting that the `:max-length` or `:max-depth` approaches are a solution to the Datomic issue, I just wanted to bring them to your attention.

**Comment by PEZ** [comment] 2019-11-08 23:25
Haha, this is awesome I was just [committing some documentation](https://github.com/BetterThanTomorrow/calva/pull/436/commits/b08d569342019466650d842b723ec5b17b3772cd) for the coming Calva pretty printing enhancements and went here for the link to this issue..

Late here, and I will have to try this out tomorrow. But it looks like the enhancements will become even better than I had hoped for!

Glad you liked the repo, btw. I wrote a small piece about it the other day: https://clojureverse.org/t/a-quick-way-to-start-experimenting-with-datomic/5004

**Comment by PEZ** [comment] 2019-11-09 12:48
Hello again. Since pretty printing is your expertise, and especially `zprint`, can you check [this page about Calva's pretty printer](https://github.com/BetterThanTomorrow/calva/blob/545d27fcfc124d8aa680f6dfcf6e216361f1fe26/docs/readthedocs/source/pprint.md) out for me? So that I do not misinform people. 😄

**Comment by kkinnear** [comment] 2019-11-09 16:01
I'm not a Calva or VStudio user, so I'm coming at this without a lot of context that you (and your users) have.  That said, looking at that page, I'm wondering about this sentence: 

> Pretty printing results on the server causes the them to be evaluated. WHich can have HUGE implications depending on the results and which printer is used.

[The "H" in which should not be capitalized.]

I guess I don't know quite what you mean here.  If you use zprint to print some structure that already exists in the repl (e.g., the results of some function evaluation), it doesn't evaluate it.  Now, if you type in the structure to the repl and don't quote it, yes it will evaluate it as it is entered into the REPL and prior to printing it.  That's not zprint, of course, that just the way the repl works. I'm not entirely certain of the environment context you are describing, so maybe your explanation actually describes what is happening and I just don't know about it.

But with the Datomic results, for instance, it isn't that the results are being evaluated, it is just that they are so __big__.  

From my standpoint (i.e., ignorance) it seems like you could spend a bit more time explaining why the "server side" pretty printing has issues.  At least for me, the current explanation doesn't seem to match my understanding.

Thanks for asking!

**Comment by PEZ** [comment] 2019-11-09 16:36
Thanks for reading and giving this feedback! Seems that it was very good that I asked. And also, maybe I haven't researched it enough. Anyway, currently with Calva, if I evaluate a transaction in the example project, with pretty printing on, I get that large result that this issue is speaking about. If I do it with my work project I never get any results, but Java starts to consume all CPU and will just keep doing that until I interrupt the evaluation.

Current Calva uses `puget` via `cider-nrepl`. If I make it use `pprint` instead, I just get that output that I also posted above. I seem to have tried with `zprint` as well according to this issue. 😄 And maybe also with `fipp`, because *something* got me to add this client side option to Calva. Maybe it is just the wording ”evaluated” is what's wrong in my text. It is more that it is ”interpolated”, or ”expanded”, maybe? But what is it that gets exapanded? Some values?

I'd love to get this right and explain it properly. But **my** ignorance is a bit in the way. How would you describe it?

**Comment by kkinnear** [comment] 2019-11-09 21:39
I'd like to help, but I don't know enough about the environment of the "example project" and how that differs from your "work project".

I understand this though:

>  if I evaluate a transaction in the example project, with pretty printing on, I get that large result that this issue is speaking about.

Yes, and now we know how to __not__ get that large result (at least with zprint).  You give zprint the options map: `{:record {:to-string? true}}`.

I have no idea what is going on here:

> If I do it with my work project I never get any results, but Java starts to consume all CPU and will just keep doing that until I interrupt the evaluation.

If this is the same evaluation, then it isn't circular, since zprint will print the value of the records in the "result" from Datomic.  I don't know what is going on in your "work project" that is different from your "example project" that would cause the pretty printing to not terminate, if indeed that is what is not finishing.  

Is this issue easy to reproduce?

Does it happen with every pretty printer?

**Comment by PEZ** [comment] 2019-11-09 21:52
I haven't tried `zprint` on my work project. Just default Calva, which is puget. Will try that now.

But you are right, circular references is just my theory, I shouldn't state it as a fact there. Will fix.

**Comment by PEZ** [comment] 2019-11-09 22:55
I have now tried with all cider-nrepl preconfigured pretty printers and with all, except `pprint`, the java process goes mad and the computer turns glowing hot.

What's more. Trying to hand zprint the `{:record {:to-string? true}}` I get this error:

```
Error printing return value at zprint.core/determine-options (core.cljc:276).
Option errors in this call: The value of the key-sequence [:record :to-string?] -> 0 was not a boolean
class clojure.lang.ExceptionInfo
```

Which is because I use bencode transport for nREPL and then boolean `false` gets encoded the same way as `0`.

**Comment by kkinnear** [comment] 2019-11-09 23:15
Ignoring the melting computer for a moment...

Can't you configure zprint with `(set-options! {:record {:to-string? true}})` before you use the library (in the code where the library executes), and not pass the options map around?

**Comment by kkinnear** [comment] 2019-11-09 23:24
On the subject of the pretty printers not terminating...

Just what are you handing to them?  Is this something that you can make happen in `nrepl-pprint-datomic`?  zprint certainly doesn't handle circular stuff, but I'm sure I could fix that -- but it would be nice to ensure that it really *would* fix this issue before I jump into that.

I'd love to be able to reproduce this problem so I could work on it...

**Comment by PEZ** [comment] 2019-11-09 23:45
> Can't you configure zprint with (set-options! {:record {:to-string? true}}) before you use the library (in the code where the library executes), and not pass the options map around?

I think.I could, but it is unclear to me right now how I would do that. I'm using zprint by proxy, via `cider-nrepl`.

> I don't think that the {:record {:to-string? true}} needs to be configurable, really. At least for now. Which is to say -- if records always print the to-string value, that would probably be ok.

Agree. This is what I tried to implement as a first version of this.

> If it would be valuable, I could relax the spec for the boolean? to accept any non-nil value

That would certainly make it easier for me.

**Comment by kkinnear** [comment] 2019-11-09 23:51
> I think.I could, but it is unclear to me right now how I would do that. I'm using zprint by proxy, via cider-nrepl.

Oh.  I'm starting to (vaguely) understand.  You aren't actually invoking it yourself.  I didn't get that before, though you have certainly said it before.  Sigh.  I'll look at relaxing the spec for boolean and see what I can do.

**Comment by PEZ** [comment] 2019-11-10 00:04
> On the subject of the pretty printers not terminating...
> Just what are you handing to them? Is this something that you can make happen in `nrepl-pprint-datomic`?

I'm just transacting some data. I get it if I do the same as with that small example project:

```clojure
@(d/transact conn [{:db/doc "Hello world"}])
```

Currently I don't know how I would reproduce it. But I get it regardless if I use a mem database or a persisting one. Hmmm, tricky one. I will have to think about it some.

However, I think the records-as-strings fix to also avoid the non-terminating problem. But I could be wrong of course.

**Comment by PEZ** [comment] 2019-11-10 00:13
> You aren't actually invoking it yourself. I didn't get that before, though you have certainly said it before. Sigh.

No probs!

`cider-nrepl` allows for providing your own print function and I think I could probably use that if need be. (Even if I don't know right now how I would do that, but it wouldn't be the first thing I had to learn on this Calva journey, haha.)

**Comment by kkinnear** [comment] 2020-01-16 02:00
I'm **_finally_** getting around to removing the boolean restrictions on the options map items that end in "...?" for zprint.  What I have implemented is that normal Clojure `nil` or `false` are false, and anything else is true.  But then I saw this from the post on Nov 9, 2019, above:

> > Error printing return value at zprint.core/determine-options (core.cljc:276).
> > Option errors in this call: The value of the key-sequence [:record :to-string?] -> 0 was not a boolean
> > class clojure.lang.ExceptionInfo
> 
> Which is because I use bencode transport for nREPL and then boolean false gets encoded the same way as 0.
> 

If you are sending a Clojure `false` and the transport turns that into a `0`, that is a whole different problem than the one I have just solved.  I was thinking that I could just not require `true` or `false`, but relax the requirement to accept anything other than `nil` or `false` for true.  But if you can't send either `nil` or `false` for false, that's a problem. I can't interpret `0` as false.  At least not in general.  I _can_ think of a way around even that, but it is a considerable amount of code and something of a monumental hack.

Please tell me that `false` doesn't turn into numeric `0`!

Or if it does, that you can somehow send `nil`.

All that said, what matters for this specific case (i.e. `{:record {:to-string? true}}`) is what does `true` turn into, since `false` is the default for `:to-string?`.  So you don't have to tell it `false`, you have to tell it `true`.    As long as that doesn't turn into `nil` or `false`, which seems unlikely, then the change I have made would work for the problem we were originally discussing.

But it would be nice to believe that, if I make this change, that you get a general solution, not just something that works for this particular situation.

**Comment by kkinnear** [comment] 2020-01-22 17:15
I'm close to starting the process to release 0.5.4, and it would be nice to know if the change I've described immediately above will actually help the situation that you have described.   Thanks!

**Comment by PEZ** [comment] 2020-01-22 19:02
Hello. My apologies for slow response!

Bencode does not have a boolean representation, so `true => 1` and `false => 0`, unfortunately. It's horrible, I know. Also `nil => 0`.

**Comment by kkinnear** [comment] 2020-01-22 20:37
SIgh.  About all I can think of to do here would be to have an options map k-v pair, say `{:interpret-as-false 0}` that, only if present, would cause me to scan the entire options map for keys that end in "?", and for all of them, if the value is a zero I would change it to false.  That way, you would say `{:interpret-as-false 0}` and then I'd do the other processing before I did the validation with spec.  Seems like a hack, but if it would make zprint work for you better, I could do this.

**Comment by PEZ** [comment] 2020-01-23 07:49
That would indeed make it zprint work for more Calva users.

The real fix is probably to make Calva use EDN transport instead, but I don't know how big such an effort is, and currently can't really fit that kind of work into my schedule.

**Comment by kkinnear** [comment] 2020-03-21 15:56
I have (finally) implemented a fix for the problem with "false".  

My explanation in the CHANGLOG.md said:

> In some cases, when specifying option maps for remote invocations of zprint, boolean `true` and `false` in the  options map turns into something other than `true` and `false` when zprint is invoked  remotely.  For instance, `true` can become `1` in the remove invocation, and `false` can become `0`.  This makes it impossible to invoke zprint with a reasonable options map, since both `1` and `0` fail to validate as they are not boolean.  Relaxing the validation rules would not help, as `0` is never going to be `false` for Clojure.
> 
> In this (rather obscure) case you could set `:coerce-to-false` to the value that you want to be `false`.  If you do this the options map you specify will be searched for all values which must be boolean.  If they are already boolean (i.e., already `true` or `false`), they are not changed.  If they are not boolean, then if they equal the value of `:coerce-to-false`, they will be set to `false`, and otherwise they will be set to `true`.
> 
>  In the example above, `{:coerce-to-false 0}` would correctly set the various boolean values.
> 
> 

This implementation is specifically to solve the problem we have discussed in this issue.  If I understand it properly (which I obviously didn't more than once as we have discussed it), then this __should__ solve the problem you have with remote invocations.  

If it doesn't, please let me know and I'll keep working on it.  

If it does, let me know too!

**Comment by kkinnear** [comment] 2022-07-27 17:18
I'm pretty sure that you don't care about this anymore.  But it has been in for a while, so I'm going to close this issue.

**Closed by kkinnear** 2022-07-27 17:18 UTC
Labels: enhancement
