### ISSUE TITLE
Allow double semicolon for !zprint comment

### ISSUE THREAD

**Issue by pesterhazy** [kkinnear/zprint#70] opened 2018-11-04 17:35 UTC
It would be great if in addition to

```
;!zprint {:format :skip}
```

the following format would be accepted

```
;;!zprint {:format :skip}
```

The reason is that Emacs considers [single-semicolon comments](https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html) in Lisps to be aligned to the right of the sourc code. Comments starting with `;;` are expected to cover the whole line.

As a result, single-semicolon comments that cover the whole line are, at least in my Emacs installation, auto-indented in unpredictable ways. `;;` OTOH comments are fine.

**Comment by kkinnear** [comment] 2018-11-04 23:29
Sure, that makes sense.   I'll do that.

It is also interesting how Emacs treats the different numbers of semicolons.  I'm about to rework the comment handling, and that might be something I would pick up on myself because the comment handling right now is less than stellar.  Part of the problem is that it is hard to tell full line from end-of-line comments.  Maybe this would be the way to do that, if I can't find a way to remember how they came in.

**Comment by pesterhazy** [comment] 2018-11-05 15:44
Personally I'm not sure how widespread the `;`/`;;` distinction is in the Clojure community, compared to the Lisp community, and whether other editors like Atom and IntelliJ know about that distinction.

**Comment by kkinnear** [comment] 2018-11-07 02:17
Fixed in 0.4.13.  Thanks for the idea.  You can now use any number of semicolons in a `;!zprint` directive.  No spaces, but any number of semicolons.

**Closed by kkinnear** 2018-11-07 02:17 UTC
Labels: enhancement

**Comment by pesterhazy** [comment] 2018-11-07 07:20
Great!
