### ISSUE TITLE
`;!zprint {:format :skip}` removes arglist when there's zero arg

### ISSUE THREAD

**Issue by yqrashawn** [kkinnear/zprint#284] opened 2023-01-05 11:31 UTC
```clojure
;!zprint {:format :skip}
(defn foo [] (prn 'a))
```
get formatted into 

```clojure
;!zprint {:format :skip}
(defn foo  (prn 'a))
```

check the video below, every time the file name at the bottom turns from red to white means there's a format applied
tested with 
```clojure
{:style [:community]
 :width 105}
```

https://user-images.githubusercontent.com/15090582/210770236-0eb1a81d-c449-46d9-9cdc-0c32aa8f9353.mp4

**Comment by kkinnear** [comment] 2023-01-05 18:40
Yes, this is a duplicate of Issue #263.  It was unfortunately added when I rewrote the skipping and no-formatting code in `1.2.4`.  It is fixed and will ship in `1.2.5`.  If you don't need something in `1.2.4`, then using `1.2.3` would make this problem go away.  Alternatively, just avoid turning off formatting (or skipping) until `1.2.5` would be the only workarounds.  #263 got closed before the fix actually shipped by the person who created the issue.  I tend to leave them open until I actually ship the fix. I'm working steadily on fixing #273, for what that is worth.

**Closed** 2023-01-06 01:36 UTC
