### ISSUE TITLE
Minor: sole comment in `when` hangs instead of indents

### ISSUE THREAD

**Issue by atdixon** [kkinnear/zprint#193] opened 2021-05-05 16:39 UTC
Very minor, not sure if this is even a bug:

```
(when true
  ; hi
  )
```

`./zprintm-1.1.1 < src/demo.clj`

```
(when true
      ; hi
)
```

---

But when the comment is not alone, then we get the body indented as expected:

```
(when true
  ; hi
  :hi
  )
```

**Comment by kkinnear** [comment] 2021-05-05 18:54
I'm not sure it is a bug either, as this is the example that convinced me to change how this was done (and to ensure that it was consistent across different styles (from Issue #143)):
```
; The old way

% ./zprintm-0.5.4 <cljfiles/i193b.clj
(a (b (c (d e
            f ;stuff
           )
         h ;foo
        ) ;bar
     )
   i
   j)

; What I have been thinking of as a better way, consistently applied across various styles:

% ./zprintm-1.1.1 <cljfiles/i193b.clj
(a (b (c (d e
            f ;stuff
         )
         h ;foo
      ) ;bar
   )
   i
   j)
```
That said, I am unable to reproduce what you have demonstrated:
```
 % cat cljfiles/i193d.clj
(when true
  ; hi
  :hi
  )
% ./zprintm-1.1.1 <cljfiles/i193d.clj
(when true
  ; hi
  :hi)
% ./zprintm-1.1.1 '{:style :respect-nl}' <cljfiles/i193d.clj
(when true
  ; hi
  :hi
)
% ./zprintm-1.1.1 '{:style :indent-only}' <cljfiles/i193d.clj
(when true
  ; hi
  :hi
)
```
I'd like to see how you are managing to *ever* get the right paren aligned with the `:hi`!   Please send me the output from this:
```
% ./zprintm-1.1.1 -e
```
which should output the elements of the options map that are different than the defaults.  That would probably tell me what I need to know to be able to reproduce the situation you are describing.

Thanks -- Kim

**Comment by kkinnear** [comment] 2022-07-27 17:19
I was unable to reproduce this, and it has been over a year, so I'm closing this issue.  If you want to work together on it, please re-open the issue.  Thanks!

**Closed by kkinnear** 2022-07-27 17:19 UTC
